import './globals.css'
import { Inter } from 'next/font/google'
import { Suspense } from 'react'
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import Header from '@/components/layout/header';

const inter = Inter({ subsets: ['latin'] })

type LayoutProps = {
  loggedUser?: string;
}

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

 const  RootLayout = async (props: LayoutProps & { children: React.ReactNode }) => {
 const session = await getServerSession(authOptions);
  
 return (
    <html lang="en">
      <body className={inter.className}>
      <Suspense fallback={<div>loading...</div>}>
          <Header />
          {props.children}
      </Suspense>
      </body>
    </html>
  )
}

export default RootLayout;
